"""users table

Revision ID: 43e4aee441ef
Revises: 4e7850f067b8
Create Date: 2020-04-08 17:57:44.211051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e4aee441ef'
down_revision = '4e7850f067b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('commentary', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_commentary'), 'user', ['commentary'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_commentary'), table_name='user')
    op.drop_column('user', 'commentary')
    # ### end Alembic commands ###
