"""users table

Revision ID: 4e7850f067b8
Revises: fc917a6e29bf
Create Date: 2020-04-08 11:17:49.443943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7850f067b8'
down_revision = 'fc917a6e29bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('login', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('picture', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_fullname'), 'user', ['fullname'], unique=True)
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.create_index(op.f('ix_user_picture'), 'user', ['picture'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_picture'), table_name='user')
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_index(op.f('ix_user_fullname'), table_name='user')
    op.drop_column('user', 'picture')
    op.drop_column('user', 'login')
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
