"""user table

Revision ID: ad7b4b7c70e9
Revises: 43e4aee441ef
Create Date: 2020-04-09 13:16:21.192483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7b4b7c70e9'
down_revision = '43e4aee441ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_commentary', table_name='user')
    op.create_index(op.f('ix_user_commentary'), 'user', ['commentary'], unique=False)
    op.drop_index('ix_user_fullname', table_name='user')
    op.create_index(op.f('ix_user_fullname'), 'user', ['fullname'], unique=False)
    op.drop_index('ix_user_login', table_name='user')
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=False)
    op.drop_index('ix_user_picture', table_name='user')
    op.create_index(op.f('ix_user_picture'), 'user', ['picture'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_picture'), table_name='user')
    op.create_index('ix_user_picture', 'user', ['picture'], unique=1)
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.create_index('ix_user_login', 'user', ['login'], unique=1)
    op.drop_index(op.f('ix_user_fullname'), table_name='user')
    op.create_index('ix_user_fullname', 'user', ['fullname'], unique=1)
    op.drop_index(op.f('ix_user_commentary'), table_name='user')
    op.create_index('ix_user_commentary', 'user', ['commentary'], unique=1)
    # ### end Alembic commands ###
